### PR TITLE
Generalized matmul

### PR DESCRIPTION
**Pull request by bj-ro**
Here's an attempt to fix the problem with m* mentioned in issue #5. It's probably not the cleanest way to do it, but it seems to work. I should however mention that I have not looked too close into how performance is affected by the changes...

### CODE REVIEW

**Comment by Shinmera** [comment]
This library is a complete mess in general, so I'm not too concerned about it being clean :)

I would like to see a basic microbenchmark comparison for the base case mat4*mat4 multiplication though. I doubt the times will change noticeably, but I'd just like to be certain.

**Comment by bj-ro** [comment]
Noted :)

I ran some simple tests with sbcl. The results change a bit from time to time, but the timings below are more or less what I get:

**Using master:**
```
(time (dotimes (i 1000) (m* (mat 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16) (mat 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1))))
Evaluation took:
  0.000 seconds of real time
  0.000157 seconds of total run time (0.000144 user, 0.000013 system)
  100.00% CPU
  543,608 processor cycles
  294,592 bytes consed
```

**Using generalized-matmul:**
```
(time (dotimes (i 1000) (m* (mat 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16) (mat 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1))))
Evaluation took:
  0.000 seconds of real time
  0.000159 seconds of total run time (0.000153 user, 0.000006 system)
  100.00% CPU
  551,944 processor cycles
  294,672 bytes consed
```

I did the same with 5x5 matrices and could not see any change.

**Comment by Shinmera** [comment]
You're going to want to put the matrix allocations outside the loop and increase the number of iterations by quite a bit still, and then run multiple times in sequence to get warmup out of the way. Finally you'll also want to use randomised matrices to eliminate possible constant factor weirdness in the hardware.
```
(dotimes (i 20)
  (let ((a (mrand 4 4))
        (b (mrand 4 4)))
    (time (dotimes (i 10000000) (m* a b)))))
```

**Comment by bj-ro** [comment]
Ok, good idea! Here's what I get, a slight increase of runtime it seems:
 
**master**:
```
(let ((a (mrand 4 4))
       (b (mrand 4 4)))
  (trivial-benchmark:with-timing (1000000) (m* a b)))
-                SAMPLES  TOTAL     MINIMUM   MAXIMUM   MEDIAN    AVERAGE   DEVIATION  
REAL-TIME        1000000  2.872038  0         0.004002  0         0.000003  0.000107   
RUN-TIME         1000000  2.800836  0.000002  0.000089  0.000003  0.000003  0.000001   
USER-RUN-TIME    1000000  1.579418  0         0.000051  0.000002  0.000002  0.000001   
SYSTEM-RUN-TIME  1000000  1.187721  0         0.000056  0         0.000001  0.000001   
PAGE-FAULTS      1000000  0         0         0         0         0         0.0        
GC-RUN-TIME      1000000  0         0         0         0         0         0.0        
BYTES-CONSED     1000000  57745600  0         131056    0         57.7456   1378.7535  
EVAL-CALLS       1000000  0         0         0         0         0         0.0        

(dotimes (i 20)
  (let ((a (mrand 4 4))
        (b (mrand 4 4)))
    (time (dotimes (i 10000000) (m* a b)))))
Evaluation took:
  0.604 seconds of real time
  0.602855 seconds of total run time (0.502287 user, 0.100568 system)
  [ Run times consist of 0.040 seconds GC time, and 0.563 seconds non-GC time. ]
  99.83% CPU
  2,120,189,606 processor cycles
  960,015,536 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439709 seconds of total run time (0.435046 user, 0.004663 system)
  [ Run times consist of 0.009 seconds GC time, and 0.431 seconds non-GC time. ]
  100.00% CPU
  1,543,277,084 processor cycles
  959,983,296 bytes consed
  
Evaluation took:
  0.444 seconds of real time
  0.445974 seconds of total run time (0.438517 user, 0.007457 system)
  [ Run times consist of 0.014 seconds GC time, and 0.432 seconds non-GC time. ]
  100.45% CPU
  1,558,500,432 processor cycles
  959,983,360 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439847 seconds of total run time (0.435998 user, 0.003849 system)
  [ Run times consist of 0.010 seconds GC time, and 0.430 seconds non-GC time. ]
  100.00% CPU
  1,542,942,406 processor cycles
  960,015,936 bytes consed
  
Evaluation took:
  0.444 seconds of real time
  0.439959 seconds of total run time (0.439959 user, 0.000000 system)
  [ Run times consist of 0.010 seconds GC time, and 0.430 seconds non-GC time. ]
  99.10% CPU
  1,542,935,376 processor cycles
  960,015,968 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.440082 seconds of total run time (0.437114 user, 0.002968 system)
  [ Run times consist of 0.010 seconds GC time, and 0.431 seconds non-GC time. ]
  100.00% CPU
  1,542,209,892 processor cycles
  959,983,232 bytes consed
  
Evaluation took:
  0.456 seconds of real time
  0.459559 seconds of total run time (0.458948 user, 0.000611 system)
  [ Run times consist of 0.014 seconds GC time, and 0.446 seconds non-GC time. ]
  100.88% CPU
  1,608,023,616 processor cycles
  960,016,032 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439622 seconds of total run time (0.431809 user, 0.007813 system)
  [ Run times consist of 0.009 seconds GC time, and 0.431 seconds non-GC time. ]
  100.00% CPU
  1,541,291,550 processor cycles
  960,016,032 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439143 seconds of total run time (0.435432 user, 0.003711 system)
  [ Run times consist of 0.009 seconds GC time, and 0.431 seconds non-GC time. ]
  99.77% CPU
  1,540,565,082 processor cycles
  959,983,328 bytes consed
  
Evaluation took:
  0.444 seconds of real time
  0.444880 seconds of total run time (0.444819 user, 0.000061 system)
  [ Run times consist of 0.015 seconds GC time, and 0.430 seconds non-GC time. ]
  100.23% CPU
  1,557,621,256 processor cycles
  959,983,376 bytes consed
  
Evaluation took:
  0.460 seconds of real time
  0.459158 seconds of total run time (0.452252 user, 0.006906 system)
  [ Run times consist of 0.010 seconds GC time, and 0.450 seconds non-GC time. ]
  99.78% CPU
  1,610,386,672 processor cycles
  960,015,936 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439440 seconds of total run time (0.439440 user, 0.000000 system)
  [ Run times consist of 0.010 seconds GC time, and 0.430 seconds non-GC time. ]
  99.77% CPU
  1,538,282,018 processor cycles
  960,015,936 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439556 seconds of total run time (0.435947 user, 0.003609 system)
  [ Run times consist of 0.010 seconds GC time, and 0.430 seconds non-GC time. ]
  100.00% CPU
  1,540,529,728 processor cycles
  959,983,232 bytes consed
  
Evaluation took:
  0.444 seconds of real time
  0.445251 seconds of total run time (0.445251 user, 0.000000 system)
  [ Run times consist of 0.015 seconds GC time, and 0.431 seconds non-GC time. ]
  100.23% CPU
  1,558,679,934 processor cycles
  959,983,296 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439703 seconds of total run time (0.436496 user, 0.003207 system)
  [ Run times consist of 0.010 seconds GC time, and 0.430 seconds non-GC time. ]
  100.00% CPU
  1,540,904,282 processor cycles
  960,016,032 bytes consed
  
Evaluation took:
  0.476 seconds of real time
  0.472949 seconds of total run time (0.472949 user, 0.000000 system)
  [ Run times consist of 0.010 seconds GC time, and 0.463 seconds non-GC time. ]
  99.37% CPU
  1,656,639,996 processor cycles
  960,016,064 bytes consed
  
Evaluation took:
  0.444 seconds of real time
  0.446124 seconds of total run time (0.441702 user, 0.004422 system)
  [ Run times consist of 0.015 seconds GC time, and 0.432 seconds non-GC time. ]
  100.45% CPU
  1,559,956,270 processor cycles
  959,983,360 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439539 seconds of total run time (0.434944 user, 0.004595 system)
  [ Run times consist of 0.010 seconds GC time, and 0.430 seconds non-GC time. ]
  100.00% CPU
  1,541,686,890 processor cycles
  960,015,936 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439739 seconds of total run time (0.439114 user, 0.000625 system)
  [ Run times consist of 0.010 seconds GC time, and 0.430 seconds non-GC time. ]
  100.00% CPU
  1,540,969,970 processor cycles
  960,015,968 bytes consed
  
Evaluation took:
  0.440 seconds of real time
  0.439538 seconds of total run time (0.435734 user, 0.003804 system)
  [ Run times consist of 0.010 seconds GC time, and 0.430 seconds non-GC time. ]
  100.00% CPU
  1,540,845,842 processor cycles
  959,983,264 bytes consed

```
**generalized-matmul**:

```
(let ((a (mrand 4 4))
       (b (mrand 4 4)))
  (trivial-benchmark:with-timing (1000000) (m* a b)))
-                SAMPLES  TOTAL     MINIMUM   MAXIMUM   MEDIAN    AVERAGE    DEVIATION  
REAL-TIME        1000000  2.824043  0         0.004001  0         0.000003   0.000106   
RUN-TIME         1000000  2.795464  0.000002  0.000023  0.000003  0.000003   0.0        
USER-RUN-TIME    1000000  1.55961   0         0.000022  0.000002  0.000002   0.000001   
SYSTEM-RUN-TIME  1000000  1.205451  0         0.000018  0         0.000001   0.000001   
PAGE-FAULTS      1000000  0         0         0         0         0          0.0        
GC-RUN-TIME      1000000  0         0         0         0         0          0.0        
BYTES-CONSED     1000000  58038912  0         131056    0         58.038914  1382.2034  
EVAL-CALLS       1000000  0         0         0         0         0          0.0        

(dotimes (i 20)
  (let ((a (mrand 4 4))
        (b (mrand 4 4)))
    (time (dotimes (i 10000000) (m* a b)))))
Evaluation took:
  0.548 seconds of real time
  0.551847 seconds of total run time (0.519232 user, 0.032615 system)
  [ Run times consist of 0.013 seconds GC time, and 0.539 seconds non-GC time. ]
  100.73% CPU
  1,927,403,486 processor cycles
  960,004,560 bytes consed
  
Evaluation took:
  0.468 seconds of real time
  0.469125 seconds of total run time (0.469011 user, 0.000114 system)
  [ Run times consist of 0.012 seconds GC time, and 0.458 seconds non-GC time. ]
  100.21% CPU
  1,637,377,200 processor cycles
  959,983,248 bytes consed
  
Evaluation took:
  0.468 seconds of real time
  0.468765 seconds of total run time (0.468715 user, 0.000050 system)
  [ Run times consist of 0.018 seconds GC time, and 0.451 seconds non-GC time. ]
  100.21% CPU
  1,630,805,300 processor cycles
  959,983,232 bytes consed
  
Evaluation took:
  0.464 seconds of real time
  0.466590 seconds of total run time (0.466220 user, 0.000370 system)
  [ Run times consist of 0.012 seconds GC time, and 0.455 seconds non-GC time. ]
  100.65% CPU
  1,626,920,280 processor cycles
  960,016,048 bytes consed
  
Evaluation took:
  0.460 seconds of real time
  0.463914 seconds of total run time (0.463315 user, 0.000599 system)
  [ Run times consist of 0.012 seconds GC time, and 0.452 seconds non-GC time. ]
  100.87% CPU
  1,617,968,560 processor cycles
  960,016,048 bytes consed
  
Evaluation took:
  0.476 seconds of real time
  0.476563 seconds of total run time (0.476553 user, 0.000010 system)
  [ Run times consist of 0.018 seconds GC time, and 0.459 seconds non-GC time. ]
  100.21% CPU
  1,659,317,718 processor cycles
  959,983,376 bytes consed
  
Evaluation took:
  0.464 seconds of real time
  0.466973 seconds of total run time (0.466543 user, 0.000430 system)
  [ Run times consist of 0.012 seconds GC time, and 0.455 seconds non-GC time. ]
  100.65% CPU
  1,628,597,678 processor cycles
  959,983,232 bytes consed
  
Evaluation took:
  0.460 seconds of real time
  0.464675 seconds of total run time (0.459948 user, 0.004727 system)
  [ Run times consist of 0.012 seconds GC time, and 0.453 seconds non-GC time. ]
  101.09% CPU
  1,620,665,906 processor cycles
  960,015,952 bytes consed
  
Evaluation took:
  0.460 seconds of real time
  0.464030 seconds of total run time (0.460208 user, 0.003822 system)
  [ Run times consist of 0.012 seconds GC time, and 0.453 seconds non-GC time. ]
  100.87% CPU
  1,618,636,270 processor cycles
  960,015,984 bytes consed
  
Evaluation took:
  0.468 seconds of real time
  0.471493 seconds of total run time (0.470982 user, 0.000511 system)
  [ Run times consist of 0.018 seconds GC time, and 0.454 seconds non-GC time. ]
  100.64% CPU
  1,639,932,580 processor cycles
  959,983,280 bytes consed
  
Evaluation took:
  0.456 seconds of real time
  0.459467 seconds of total run time (0.458961 user, 0.000506 system)
  [ Run times consist of 0.012 seconds GC time, and 0.448 seconds non-GC time. ]
  100.66% CPU
  1,602,428,126 processor cycles
  959,983,264 bytes consed
  
Evaluation took:
  0.468 seconds of real time
  0.469422 seconds of total run time (0.469422 user, 0.000000 system)
  [ Run times consist of 0.012 seconds GC time, and 0.458 seconds non-GC time. ]
  100.21% CPU
  1,638,006,962 processor cycles
  960,016,048 bytes consed
  
Evaluation took:
  0.472 seconds of real time
  0.475313 seconds of total run time (0.475313 user, 0.000000 system)
  [ Run times consist of 0.018 seconds GC time, and 0.458 seconds non-GC time. ]
  100.64% CPU
  1,654,436,922 processor cycles
  959,983,376 bytes consed
  
Evaluation took:
  0.468 seconds of real time
  0.469796 seconds of total run time (0.466279 user, 0.003517 system)
  [ Run times consist of 0.012 seconds GC time, and 0.458 seconds non-GC time. ]
  100.43% CPU
  1,637,616,730 processor cycles
  959,983,168 bytes consed
  
Evaluation took:
  0.468 seconds of real time
  0.467849 seconds of total run time (0.460634 user, 0.007215 system)
  [ Run times consist of 0.012 seconds GC time, and 0.456 seconds non-GC time. ]
  100.00% CPU
  1,631,570,042 processor cycles
  960,015,952 bytes consed
  
Evaluation took:
  0.464 seconds of real time
  0.468485 seconds of total run time (0.467813 user, 0.000672 system)
  [ Run times consist of 0.012 seconds GC time, and 0.457 seconds non-GC time. ]
  100.86% CPU
  1,634,813,854 processor cycles
  960,016,016 bytes consed
  
Evaluation took:
  0.468 seconds of real time
  0.469797 seconds of total run time (0.469583 user, 0.000214 system)
  [ Run times consist of 0.018 seconds GC time, and 0.452 seconds non-GC time. ]
  100.43% CPU
  1,634,480,982 processor cycles
  959,983,280 bytes consed
  
Evaluation took:
  0.468 seconds of real time
  0.470095 seconds of total run time (0.465828 user, 0.004267 system)
  [ Run times consist of 0.012 seconds GC time, and 0.459 seconds non-GC time. ]
  100.43% CPU
  1,639,297,332 processor cycles
  959,983,328 bytes consed
  
Evaluation took:
  0.460 seconds of real time
  0.462280 seconds of total run time (0.459996 user, 0.002284 system)
  [ Run times consist of 0.012 seconds GC time, and 0.451 seconds non-GC time. ]
  100.43% CPU
  1,613,368,864 processor cycles
  960,016,032 bytes consed
  
Evaluation took:
  0.476 seconds of real time
  0.478221 seconds of total run time (0.477936 user, 0.000285 system)
  [ Run times consist of 0.018 seconds GC time, and 0.461 seconds non-GC time. ]
  100.42% CPU
  1,664,529,370 processor cycles
  960,016,112 bytes consed
```

**Comment by Shinmera** [comment]
Hmm, I'm not sure, it might be within measurement noise still. Unless you have a system where nothing else but SBCL runs it's hard to say what's going on with such small steps. Allocation performed by m* also still plays a big factor.

**Comment by Shinmera** [comment]
I think I'm going to merge this. If you want to tinker around with performance measurements more, feel free, though.

Thanks a lot for all your work!

**Comment by bj-ro** [comment]
I think I'll leave it at that for now.

Thank you for all your work, I'm glad I could contribute something :)

**Pull request merged**
